name: CI

on:
  push:
      branches: [develop]
  pull_request:
      branches: [develop]

jobs:
  build:
    # FIXME: This builds with macOS 10.15. Move this to the 11.0 builders when possible. (See: https://github.com/actions/virtual-environments/issues/2486)
    runs-on:  macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pod install && ./other/download_libs.sh
          brew install create-dmg
        
      - name: Build
        run: |
          xcodebuild -workspace iina.xcworkspace -scheme iina CODE_SIGNING_ALLOWED=NO
          create-dmg --app-drop-link 600 185 /users/runner/IINA.dmg /Users/runner/Library/Developer/Xcode/DerivedData/iina*/Build/Products/Debug/IINA.app
        
      - name: macOS - Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: IINA.dmg
          path: /users/runner/IINA.dmg
